#!/bin/bash
USER=$(whoami)

docker run \
  -v /dev/shm:/dev/shm \
  -w /home/$USER \
  --device=/dev/kfd \
  --device=/dev/dri
    # Use this instead for partial GPU access (Numbers starts from 128)
    #   --device=/dev/dri/renderD128 \
    #   --device=/dev/dri/renderD129 \
    #   --device=/dev/dri/renderD130 \
    #   --device=/dev/dri/renderD131 \
  --group-add video \
  --security-opt seccomp=unconfined \
  -it \
  --network=host \
  --name="automoe" \
  your_docker_image