#!/bin/bash

# Default values
DEFAULT_CONTAINER_NAME="my_container"
DEFAULT_IMAGE_NAME="rocm/pytorch"

# Function to display usage
usage() {
  echo "Usage: $0 [-n container_name] [-i image_name]"
  exit 1
}

# Parse command-line options
while getopts ":n:i:" opt; do
  case ${opt} in
    n )
      CONTAINER_NAME=$OPTARG
      ;;
    i )
      IMAGE_NAME=$OPTARG
      ;;
    \? )
      echo "Invalid option: -$OPTARG" 1>&2
      usage
      ;;
    : )
      echo "Invalid option: -$OPTARG requires an argument" 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# Set default values if not provided
CONTAINER_NAME=${CONTAINER_NAME:-$DEFAULT_CONTAINER_NAME}
IMAGE_NAME=${IMAGE_NAME:-$DEFAULT_IMAGE_NAME}

USER=$(whoami)

docker run \
  -v /dev/shm:/dev/shm \
  -w /home/$USER \
  --device=/dev/kfd \
  --device=/dev/dri \
    # Use this instead for partial GPU access (Numbers starts from 128)
    #   --device=/dev/dri/renderD128 \
    #   --device=/dev/dri/renderD129 \
    #   --device=/dev/dri/renderD130 \
    #   --device=/dev/dri/renderD131 \
  --group-add video \
  --security-opt seccomp=unconfined \
  -it \
  --network=host \
  --name="$CONTAINER_NAME" \
  $IMAGE_NAME