#!/bin/bash

# Default values
DEFAULT_CONTAINER_NAME="my_container"
DEFAULT_IMAGE_NAME="rocm/pytorch"

# Function to display usage
usage() {
  echo "Usage: $0 [-n container_name] [-i image_name]"
  exit 1
}

# Parse command-line options
while getopts ":n:i:" opt; do
  case ${opt} in
    n )
      CONTAINER_NAME=$OPTARG
      ;;
    i )
      IMAGE_NAME=$OPTARG
      ;;
    \? )
      echo "Invalid option: -$OPTARG" 1>&2
      usage
      ;;
    : )
      echo "Invalid option: -$OPTARG requires an argument" 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# Set default values if not provided
CONTAINER_NAME=${CONTAINER_NAME:-$DEFAULT_CONTAINER_NAME}
IMAGE_NAME=${IMAGE_NAME:-$DEFAULT_IMAGE_NAME}

# Ensure the IMAGE_NAME is provided
if [ -z "$IMAGE_NAME" ]; then
  echo "Error: Docker image name is required."
  usage
fi

USER=$(whoami)

# Run the docker command
docker run \
  -v /dev/shm:/dev/shm \
  -w /home/$USER \
  --device=/dev/kfd \
  --device=/dev/dri \
  --group-add video \
  --security-opt seccomp=unconfined \
  -it \
  --network=host \
  --name="$CONTAINER_NAME" \
  "$IMAGE_NAME"
